spring:
  profiles:
    active: window-dev

---
server:
  port : 6010

logging:
  level:
    yongs:
      temp: DEBUG
      
app:
  datasource:
    jdbc-url: jdbc:mariadb://localhost:3306/demo
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5
      
spring:
  profiles: window-dev
  application:
    name: yongs-user
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://localhost:9411/
          
eureka:
  instance:
    preferIpAddress: true
    hostname: localhost
  client:
    registerWithEureka: true 
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/  
---
server:
  port : 6010
              
logging:
  level:
    yongs:
      temp: DEBUG

app:
  datasource:
    jdbc-url: jdbc:mariadb://maria-db:3306/demo
    driverClassName: org.mariadb.jdbc.Driver
    username: scott
    password: tiger
    maximum-pool-size: 5
    
spring:
  profiles: docker-dev
  application:
    name: yongs-user
  sleuth:
    sampler:
      probability: 1
  zipkin:
    baseUrl: http://zipkin-server:9411/
                         
eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-server
  client:
    registerWithEureka: true 
    fetchRegistry: true
    enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
      
